### ISSUE TITLE
Thank you for this project :)

### ISSUE THREAD

**Issue by username0136** [xyzuniverse/keybox-overlay-generator#1]
You saved me 10+ minutes or maybe even hours, because I wasn't able to figure out the formatting, thanks a lot.

**Comment by username0136** [comment]
You had no contact links or anything available on your profile, so I created this issue to convey my message, I hope you don't mind me doing that lol.

**Comment by xyzuniverse** [comment]
You're welcome :) Just contact me on telegram: t.me/rthedream
